# Generated by Django 2.0.4 on 2018-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homes',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
