# Generated by Django 2.0.2 on 2018-05-29 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20180413_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('checkIn', models.DateTimeField(verbose_name='check in')),
                ('checkOut', models.DateTimeField(verbose_name='check out')),
                ('bookingId', models.IntegerField(primary_key=True, serialize=False)),
                ('homeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homes.Homes')),
            ],
        ),
    ]
