# Generated by Django 2.0.2 on 2018-05-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
